common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    camera_topic: "/camera/color/image_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 4
    blind: 0.5

color_mapping:
    K_camera: [897.2655639648438, 0.0, 667.4661254882813,
               0.0, 897.6438598632813, 383.1944580078125,
               0.0, 0.0, 1.0]
    D_camera: [0.16910859942436218, -0.5095232725143433, -0.0025386682245880365, 0.0001707322953734547, 0.4606553614139557]
    time_offset_lidar_to_camera: 0.0                # ms
    extrinsic_T: [0.06760859628425592, -0.0007961934446430777, -0.06867792485862072]          # lidar to camera
    extrinsic_R: [0.0378944,   0.00118166,     0.999281,
                  -0.998785,   -0.0314839,    0.0379129,
                  0.0315061,    -0.999504,  -1.28427e-05]

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
